### ISSUE TITLE
Upgrade Apollo to latest Laravel & Statamic

### ISSUE THREAD

**Issue by techenby** [SGDInstitute/apollo#32]
- [x] [Upgrade to Laravel 8]( #30 )
- [x] [Upgrade to PHP 8.1]( #30 )
- [x] [Upgrade to Laravel 9]( #33 )
- [x] [Upgrade to Statamic 3.1]( #33 )
- [x] [Upgrade to Statamic 3.2]( #33 )
- [x] [Upgrade to Statamic 3.3]( #33 )
- [x] [Upgrade to Statamic 3.4]( #34 )
  - [x] Update lead bard modifier
- [x] Switch from Mix to Vite
